name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: restore dependencies
        uses: bahmutov/npm-install@v1
      - run: yarn lint:all
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: restore dependencies
        uses: bahmutov/npm-install@v1
      - run: yarn test
  type_check:
    name: type check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: restore dependencies
        uses: bahmutov/npm-install@v1
      - run: yarn type-check
